"use client";
import { useState, type ReactNode } from "react";
import type { MaxxingPlan } from "@hackmaxx/shared";
import {
  IconZap,
  IconCopy,
  IconCheck,
  IconExternalLink,
  IconLayers,
  IconMoney,
  IconDeadline,
  IconReuse,
  IconQuote,
} from "./Icons";
import { getPlatformBadgeStyle } from "./HackathonCard";
import { WorthScoreGlyph } from "./WorthScoreGauge";
import { useCurrency } from "../lib/currency";
import { Button } from "./ui/button";

const EFFORT_NOTE = {
  Low: "minor pitch & UI tweaks",
  Medium: "moderate feature rework",
  High: "heavy core rework",
} as const;

/** Effort reads as cost: low = win, medium = money, high = deadline. */
const EFFORT_BADGE = {
  Low: "bg-win/14 text-win border-win/40",
  Medium: "bg-money/14 text-money border-money/40",
  High: "bg-deadline/14 text-deadline border-deadline/40",
} as const;

/** One KPI tile — the four were previously inlined copies of each other. */
function Kpi({
  icon,
  label,
  value,
  unit,
  tone,
  small = false,
}: {
  icon: ReactNode;
  label: string;
  value: string;
  unit?: string;
  tone: string;
  small?: boolean;
}) {
  return (
    <div className="rounded-lg border border-border bg-card/70 p-3.5">
      <span
        className={`flex items-center gap-1 text-[11px] font-bold tracking-wider uppercase ${tone}`}
      >
        {icon}
        <span className="truncate">{label}</span>
      </span>
      <span
        className={`mt-1 block truncate font-mono font-black tabular-nums ${
          small ? "text-sm" : "text-xl sm:text-2xl"
        } ${tone}`}
      >
        {value}
        {unit && <span className="ml-1 font-sans text-[11px] font-semibold opacity-70">{unit}</span>}
      </span>
    </div>
  );
}

export function MaxxingStrategyPanel({
  strategy,
  plan,
}: {
  strategy: string;
  plan?: MaxxingPlan;
}) {
  const [copied, setCopied] = useState(false);
  const { format } = useCurrency();

  const formattedStrategy = strategy
    ? strategy.replace(/₹([\d,]+)/g, (_, match) => format(Number(match.replace(/,/g, ""))))
    : strategy;

  function copyToClipboard() {
    if (!plan) return;
    const text = [
      `# ⚡ HackMaxx Portfolio Plan`,
      `Total Expected Value: ${format(plan.total_expected_value_inr)}`,
      `Strategy: ${formattedStrategy}`,
      ``,
      `## Submission Pipeline (Deadline Order):`,
      ...plan.steps.map(
        (s, i) =>
          `${i + 1}. [${s.title}](${s.url}) — ${s.days_left}d left | Worth: ${s.worth}/100 | EV: ${format(s.expected_value_inr)} (${s.effort} effort: ${EFFORT_NOTE[s.effort]})`
      ),
      ``,
      `Generated by HackMaxx (AWS Bedrock Titan + Claude)`,
    ].join("\n");

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const steps = plan?.steps ?? [];
  const maxDays = steps.length > 0 ? Math.max(...steps.map((s) => s.days_left)) : 0;

  return (
    <section className="strategy-bg rounded-2xl border border-primary/25 shadow-2xl p-5 sm:p-7 relative overflow-hidden">
      {/* Ambient background glow */}
      <div className="absolute top-0 right-0 size-96 bg-primary/10 rounded-full blur-3xl pointer-events-none -mr-20 -mt-20" />

      <div className="relative space-y-6">
        {/* Header with Title and Copy button */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-base-content/10 pb-4">
          <div className="flex items-center gap-2.5">
            <div className="size-9 rounded-xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center text-white shadow-lg shadow-primary/30">
              <IconZap className="size-5 text-white" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="font-display text-xl sm:text-2xl font-extrabold tracking-tight">
                  Maxxing{" "}
                  <span className="font-serif italic font-normal text-2xl sm:text-3xl grad-text">
                    Strategy & Plan
                  </span>
                </h2>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-secondary/15 text-secondary border border-secondary/30">
                  AI Orchestrated
                </span>
              </div>
              <p className="text-xs text-base-content/60">
                Optimized submission roadmap to maximize your cumulative portfolio expected value
              </p>
            </div>
          </div>

          {plan && steps.length > 0 && (
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={copyToClipboard}
              className="rounded-xl border-base-content/15 bg-base-200/80 hover:bg-base-300 text-xs font-semibold gap-1.5 self-start sm:self-auto"
            >
              {copied ? (
                <>
                  <IconCheck className="size-3.5 text-success" />
                  <span className="text-success">Copied to Clipboard!</span>
                </>
              ) : (
                <>
                  <IconCopy className="size-3.5" />
                  <span>Copy Plan</span>
                </>
              )}
            </Button>
          )}
        </div>

        {/* Executive KPI Stat Cards */}
        {plan && (
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <Kpi icon={<IconMoney className="size-3" />} tone="text-money" value={format(plan.total_expected_value_inr)} label="Total Exp. Value" />
            <Kpi icon={<IconLayers className="size-3" />} tone="text-action" value={`${steps.length}`} unit={steps.length === 1 ? "Hackathon" : "Hackathons"} label="Target Submissions" />
            <Kpi icon={<IconDeadline className="size-3" />} tone="text-data" value={`${maxDays}`} unit="Days" label="Execution Window" />
            <Kpi icon={<IconReuse className="size-3" />} tone="text-win" value="High Reuse" label="Effort Strategy" small />
          </div>
        )}

        {/* Strategy Narrative */}
        <div className="flex items-start gap-3 rounded-xl border border-l-2 border-border border-l-action/60 bg-muted/60 p-4 text-sm leading-relaxed text-base-content/85">
          <IconQuote className="mt-1 size-4 shrink-0 text-action" />
          <div className="space-y-1">
            <span className="block text-xs font-bold tracking-wider text-action uppercase">
              Bedrock Strategy Summary
            </span>
            <p className="text-sm">{formattedStrategy}</p>
          </div>
        </div>

        {/* Interactive Step-by-Step Submission Timeline */}
        {steps.length > 0 && (
          <div className="space-y-3">
            <h3 className="flex items-center gap-2 font-display text-sm font-bold tracking-wider text-base-content/70 uppercase">
              <IconDeadline className="size-4 text-action" />
              Submission Pipeline (Ordered by Deadline)
            </h3>

            <div className="relative space-y-3 pl-6 before:absolute before:top-3 before:bottom-3 before:left-3.5 before:w-0.5 before:content-[''] before:bg-gradient-to-b before:from-action before:via-data before:to-action/20">
              {steps.map((s, i) => {
                const effortBadge = EFFORT_BADGE[s.effort];
                const stepUrgent = s.days_left <= 3;

                return (
                  <div
                    key={s.hackathon_id}
                    className="card-in relative rounded-xl border border-border bg-card/80 p-4 transition-all duration-200 hover:border-action/45"
                    style={{ animationDelay: `${i * 60}ms` }}
                  >
                    {/* Glowing timeline node */}
                    <div className="absolute -left-[31px] top-4 flex size-5 items-center justify-center rounded-full border-2 border-action bg-background">
                      <span className="size-2 rounded-full bg-action" />
                    </div>

                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                      <div className="space-y-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="rounded-md bg-action/15 px-2 py-0.5 font-mono text-[10px] font-bold text-action">
                            Step {i + 1}
                          </span>
                          <a
                            href={s.url}
                            target="_blank"
                            rel="noreferrer"
                            className="flex items-center gap-1.5 font-display text-base font-bold text-base-content transition-colors hover:text-action"
                          >
                            <span>{s.title}</span>
                            <IconExternalLink className="size-3.5 text-muted-foreground transition-colors group-hover:text-action" />
                          </a>
                        </div>

                        <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                          <span
                            className={`flex items-center gap-1 font-semibold ${
                              stepUrgent ? "text-deadline" : "text-money"
                            }`}
                          >
                            {stepUrgent ? <IconZap className="size-3" /> : <IconDeadline className="size-3" />}
                            <span className="font-mono tabular-nums">{s.days_left}d left</span>
                          </span>
                          <span>·</span>
                          <span className="font-mono font-semibold tabular-nums text-money">
                            EV: {format(s.expected_value_inr)}
                          </span>
                          <span>·</span>
                          <span className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold ${effortBadge}`}>
                            {s.effort} effort ({EFFORT_NOTE[s.effort]})
                          </span>
                        </div>
                      </div>

                      <div className="flex items-center gap-3 self-end sm:self-center">
                        <div className="text-right">
                          <span className="block text-[10px] font-bold text-muted-foreground uppercase">
                            Worth
                          </span>
                          <WorthScoreGlyph worth={s.worth} className="text-base" />
                        </div>
                        <Button
                          asChild
                          variant="ghost"
                          size="icon-sm"
                          className="rounded-lg hover:bg-action/10 hover:text-action"
                        >
                          <a href={s.url} target="_blank" rel="noreferrer" aria-label={`Open ${s.title}`}>
                            <IconExternalLink className="size-4" />
                          </a>
                        </Button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
