"use client";
import React, { useState } from "react";
import type { MaxxingPlan } from "@hackmaxx/shared";
import {
  IconZap,
  IconTrophy,
  IconCalendar,
  IconCopy,
  IconCheck,
  IconSparkles,
  IconExternalLink,
  IconTrendingUp,
  IconLayers,
} from "./Icons";
import { getPlatformBadgeStyle } from "./HackathonCard";

const EFFORT_NOTE = {
  Low: "minor pitch & UI tweaks",
  Medium: "moderate feature rework",
  High: "heavy core rework",
} as const;

export function MaxxingStrategyPanel({
  strategy,
  plan,
}: {
  strategy: string;
  plan?: MaxxingPlan;
}): React.JSX.Element {
  const [copied, setCopied] = useState(false);

  function copyToClipboard() {
    if (!plan) return;
    const text = [
      `# ⚡ HackMaxx Portfolio Plan`,
      `Total Expected Value: ₹${plan.total_expected_value_inr.toLocaleString("en-IN")}`,
      `Strategy: ${strategy}`,
      ``,
      `## Submission Pipeline (Deadline Order):`,
      ...plan.steps.map(
        (s, i) =>
          `${i + 1}. [${s.title}](${s.url}) — ${s.days_left}d left | Worth: ${s.worth}/100 | EV: ₹${s.expected_value_inr.toLocaleString("en-IN")} (${s.effort} effort: ${EFFORT_NOTE[s.effort]})`
      ),
      ``,
      `Generated by HackMaxx (AWS Bedrock Titan + Claude)`,
    ].join("\n");

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const steps = plan?.steps ?? [];
  const maxDays = steps.length > 0 ? Math.max(...steps.map((s) => s.days_left)) : 0;

  return (
    <section className="strategy-bg rounded-2xl border border-primary/25 shadow-2xl p-5 sm:p-7 relative overflow-hidden">
      {/* Ambient background glow */}
      <div className="absolute top-0 right-0 w-96 h-96 bg-primary/10 rounded-full blur-3xl pointer-events-none -mr-20 -mt-20" />

      <div className="relative space-y-6">
        {/* Header with Title and Copy button */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-base-content/10 pb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center text-white shadow-lg shadow-primary/30">
              <IconZap className="w-5 h-5 text-white" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="font-display text-xl sm:text-2xl font-extrabold tracking-tight">
                  Maxxing{" "}
                  <span className="font-serif italic font-normal text-2xl sm:text-3xl grad-text">
                    Strategy & Plan
                  </span>
                </h2>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-secondary/15 text-secondary border border-secondary/30">
                  AI Orchestrated
                </span>
              </div>
              <p className="text-xs text-base-content/60">
                Optimized submission roadmap to maximize your cumulative portfolio expected value
              </p>
            </div>
          </div>

          {plan && steps.length > 0 && (
            <button
              type="button"
              onClick={copyToClipboard}
              className="btn btn-sm rounded-xl border-base-content/15 bg-base-200/80 hover:bg-base-300 text-xs font-semibold gap-1.5 self-start sm:self-auto"
            >
              {copied ? (
                <>
                  <IconCheck className="w-3.5 h-3.5 text-success" />
                  <span className="text-success">Copied to Clipboard!</span>
                </>
              ) : (
                <>
                  <IconCopy className="w-3.5 h-3.5" />
                  <span>Copy Plan</span>
                </>
              )}
            </button>
          )}
        </div>

        {/* Executive KPI Stat Cards */}
        {plan && (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {/* Total Expected Value */}
            <div className="p-3.5 rounded-xl bg-base-100/60 border border-base-content/10 backdrop-blur-sm">
              <span className="text-[11px] uppercase tracking-wider font-bold text-accent flex items-center gap-1">
                <IconTrendingUp className="w-3 h-3 text-accent" /> Total Exp. Value
              </span>
              <span className="font-mono text-xl sm:text-2xl font-black tabular-nums text-accent block mt-1">
                ₹{plan.total_expected_value_inr.toLocaleString("en-IN")}
              </span>
            </div>

            {/* Target Submissions */}
            <div className="p-3.5 rounded-xl bg-base-100/60 border border-base-content/10 backdrop-blur-sm">
              <span className="text-[11px] uppercase tracking-wider font-bold text-primary flex items-center gap-1">
                <IconLayers className="w-3 h-3 text-primary" /> Target Submissions
              </span>
              <span className="font-mono text-xl sm:text-2xl font-black tabular-nums text-primary block mt-1">
                {steps.length} Hackathon{steps.length === 1 ? "" : "s"}
              </span>
            </div>

            {/* Time Window */}
            <div className="p-3.5 rounded-xl bg-base-100/60 border border-base-content/10 backdrop-blur-sm">
              <span className="text-[11px] uppercase tracking-wider font-bold text-secondary flex items-center gap-1">
                <IconCalendar className="w-3 h-3 text-secondary" /> Execution Window
              </span>
              <span className="font-mono text-xl sm:text-2xl font-black tabular-nums text-secondary block mt-1">
                {maxDays} Days
              </span>
            </div>

            {/* Reuse ROI */}
            <div className="p-3.5 rounded-xl bg-base-100/60 border border-base-content/10 backdrop-blur-sm">
              <span className="text-[11px] uppercase tracking-wider font-bold text-success flex items-center gap-1">
                <IconSparkles className="w-3 h-3 text-success" /> Effort Strategy
              </span>
              <span className="text-sm font-bold text-success block mt-1.5 truncate">
                High Reuse Focus
              </span>
            </div>
          </div>
        )}

        {/* Strategy Narrative */}
        <div className="p-4 rounded-xl bg-base-300/80 border border-base-content/10 text-sm leading-relaxed text-base-content/85 flex items-start gap-3">
          <IconSparkles className="w-4 h-4 text-primary flex-none mt-1" />
          <div className="space-y-1">
            <span className="font-bold text-xs uppercase tracking-wider text-primary block">
              Bedrock Strategy Summary
            </span>
            <p className="text-sm">{strategy}</p>
          </div>
        </div>

        {/* Interactive Step-by-Step Submission Timeline */}
        {steps.length > 0 && (
          <div className="space-y-3">
            <h3 className="font-display text-sm font-bold uppercase tracking-wider text-base-content/70 flex items-center gap-2">
              <IconCalendar className="w-4 h-4 text-primary" />
              Submission Pipeline (Ordered by Deadline)
            </h3>

            <div className="relative pl-6 space-y-3 before:content-[''] before:absolute before:left-3.5 before:top-3 before:bottom-3 before:w-0.5 before:bg-gradient-to-b before:from-primary before:via-secondary before:to-primary/20">
              {steps.map((s, i) => {
                const effortBadge = {
                  Low: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
                  Medium: "bg-amber-500/15 text-amber-400 border-amber-500/30",
                  High: "bg-rose-500/15 text-rose-400 border-rose-500/30",
                }[s.effort];

                return (
                  <div
                    key={s.hackathon_id}
                    className="card-in relative rounded-xl border border-base-content/12 bg-base-100/80 backdrop-blur-sm p-4 hover:border-primary/40 transition-all duration-200"
                    style={{ animationDelay: `${i * 60}ms` }}
                  >
                    {/* Glowing timeline node */}
                    <div className="absolute -left-[31px] top-4 w-5 h-5 rounded-full bg-base-100 border-2 border-primary flex items-center justify-center">
                      <span className="w-2 h-2 rounded-full bg-primary" />
                    </div>

                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                      <div className="space-y-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="px-2 py-0.5 rounded-md text-[10px] font-bold bg-primary/20 text-primary font-mono">
                            Step {i + 1}
                          </span>
                          <a
                            href={s.url}
                            target="_blank"
                            rel="noreferrer"
                            className="font-display text-base font-bold text-base-content hover:text-primary transition-colors flex items-center gap-1.5"
                          >
                            <span>{s.title}</span>
                            <IconExternalLink className="w-3.5 h-3.5 text-base-content/40 hover:text-primary" />
                          </a>
                        </div>

                        <div className="flex flex-wrap items-center gap-2 text-xs text-base-content/65">
                          <span className="font-semibold text-warning flex items-center gap-1">
                            <IconCalendar className="w-3 h-3" /> {s.days_left}d left
                          </span>
                          <span>·</span>
                          <span className="font-mono font-semibold text-accent">
                            EV: ₹{s.expected_value_inr.toLocaleString("en-IN")}
                          </span>
                          <span>·</span>
                          <span className={`px-2 py-0.2 rounded-full text-[10px] font-semibold border ${effortBadge}`}>
                            {s.effort} effort ({EFFORT_NOTE[s.effort]})
                          </span>
                        </div>
                      </div>

                      <div className="flex items-center gap-2 self-end sm:self-center">
                        <div className="text-right">
                          <span className="text-[10px] uppercase font-bold text-base-content/40 block">
                            Worth Score
                          </span>
                          <span className="font-mono font-extrabold text-sm text-primary">
                            {s.worth}/100
                          </span>
                        </div>
                        <a
                          href={s.url}
                          target="_blank"
                          rel="noreferrer"
                          className="btn btn-ghost btn-sm rounded-lg hover:bg-primary/10 hover:text-primary"
                        >
                          <IconExternalLink className="w-4 h-4" />
                        </a>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
